spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
  redis:
    host:
    port:
    password:
  rabbitmq:
    host:
    port:
    username:
    password:
    publisher-confirm-type: CORRELATED  #发布确认模式，消息是否被成功发送到交换机
    publisher-returns: true
    listener:
      simple:
        prefetch: 1
        concurrency: 3
        acknowledge-mode: manual   #消费端手动确认
  servlet:
    multipart:
      max-file-size: 10MB   # 单个文件上传的最大上限
      max-request-size: 100MB  # 整个请求体的最大上限
  mail:
    host:
    # 发送者邮箱
    username:
    # 配置密码,注意不是真正的密码，而是刚刚申请到的授权码
#    password:
    password:
    # 端口号
    port:
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 其他参数
    properties:
      mail:
        # 配置SSL 加密工厂
        smtp:
          ssl:
            # 本地测试，先放开ssl
            enable: true
          # 开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

cusob:
  url: https://www.cusob.com
  host: http://www.cusob.com:8080
  phone:
  cf-secret-key:
  website: www.cusob.com
  jwt:
    # 设置jwt签名加密时使用的秘钥
    secret-key:
    # 设置jwt过期时间
    ttl: # 14天
    # 设置前端传递过来的令牌名称
    token-name:
  email:
    brooks:
    daybreak:
  domain:
    spf:
    mx: mail.email-marketing-hub.com.
    smtp: mail.email-marketing-hub.com
    imap: mail.email-marketing-hub.com
    dkim:
      selector:
      prefix:

paypal:
  client:
    app:
    secret:
  mode: live
stripe:
  successUrl: https://www.cusob.com/dashboard
  cancelUrl: https://www.cusob.com/pricing