declare module Order {
  type OrderNew = {
    accountAddressLine1: string,
    accountAddressLine2: string,
    accountCity: string,
    accountCompany: string,
    accountEmail: string,
    accountFirstName: string,
    accountLastName: string,
    accountPhone: string,
    accountCountry: string,
    accountState: string,
    accountZipCode: string,
    billingAddressLine1: string,
    billingAddressLine2: string,
    billingCity: string,
    billingCompany: string,
    billingEmail: string,
    billingFirstName: string,
    billingLastName: string,
    billingPhone: string,
    billingState: string,
    billingZipCode: string,
    billingCountry: string,
    paymentMethod: number,
  }

  type orderHistory = {
    contactCapacity: number,
    createTime: string,
    discounts: number,
    emailCapacity: number,
    id: number,
    orderId: number,
    paymentMethod: number,
    planId: number,
    planName: string,
    price: number,
    tax: number,
    totalAmount: number,
    updateTime: string,
    userId: number,
  }
}